import DisplayMatrixInterface from "../interfaces/DisplayMatrixInterface.js";
import SVGType from "../interfaces/SVGTypeEnum.js";

const displayMatrix: DisplayMatrixInterface = {
  // global settings
  multistep: true, // group reagents by step
  condition: true,
  temperature: true,
  duration: true,
  solvent: true,
  svg_type: SVGType.KETCHER1,
  elementMargin: 50,
  //settings for each sample
  samples: {
    "918": {
      coefficient: true,
      yield_equivalent: true,
      molecule_sum_formula: true,
      sample_short_label: false,
      sample_name: true,
      sample_external_label: true,
      molecule_name: false,
      sample_index: true,
      svg: true,
    },
    "921": {
      coefficient: true,
      yield_equivalent: true,
      molecule_sum_formula: true,
      sample_short_label: false,
      sample_name: true,
      sample_external_label: true,
      molecule_name: false,
      sample_index: true,
      svg: true,
    },
    "922": {
      coefficient: true,
      yield_equivalent: true,
      molecule_sum_formula: true,
      sample_short_label: false,
      sample_name: true,
      sample_external_label: true,
      molecule_name: false,
      sample_index: true,
      svg: true,
    },
    "923": {
      coefficient: true,
      yield_equivalent: true,
      molecule_sum_formula: true,
      sample_short_label: false,
      sample_name: true,
      sample_external_label: true,
      molecule_name: false,
      sample_index: true,
      svg: true,
    },
    "924": {
      coefficient: true,
      yield_equivalent: true,
      molecule_sum_formula: true,
      sample_short_label: false,
      sample_name: true,
      sample_external_label: true,
      molecule_name: false,
      sample_index: true,
      svg: true,
    },
    "925": {
      coefficient: true,
      yield_equivalent: true,
      molecule_sum_formula: true,
      sample_short_label: false,
      sample_name: true,
      sample_external_label: true,
      molecule_name: false,
      sample_index: true,
      svg: true,
    },
    "926": {
      coefficient: true,
      yield_equivalent: true,
      molecule_sum_formula: true,
      sample_short_label: false,
      sample_name: true,
      sample_external_label: true,
      molecule_name: false,
      sample_index: true,
      svg: true,
    },
    "927": {
      coefficient: true,
      yield_equivalent: true,
      molecule_sum_formula: true,
      sample_short_label: false,
      sample_name: true,
      sample_external_label: true,
      molecule_name: false,
      sample_index: true,
      svg: true,
    },
    "1843": {
      coefficient: true,
      yield_equivalent: false,
      molecule_sum_formula: true,
      sample_short_label: false,
      sample_name: true,
      sample_external_label: true,
      molecule_name: false,
      sample_index: true,
      svg: true,
    },

    "1844": {
      coefficient: true,
      yield_equivalent: true,
      molecule_sum_formula: true,
      sample_short_label: false,
      sample_name: true,
      sample_external_label: true,
      molecule_name: false,
      sample_index: true,
      svg: true,
    },
    "1845": {
      coefficient: true,
      yield_equivalent: true,
      molecule_sum_formula: true,
      sample_short_label: false,
      sample_name: true,
      sample_external_label: true,
      molecule_name: false,
      sample_index: true,
      svg: true,
    },
    "1846": {
      coefficient: true,
      yield_equivalent: true,
      molecule_sum_formula: true,
      sample_short_label: false,
      sample_name: true,
      sample_external_label: true,
      molecule_name: false,
      sample_index: true,
      svg: true,
    },
    "1847": {
      coefficient: true,
      yield_equivalent: true,
      molecule_sum_formula: true,
      sample_short_label: false,
      sample_name: true,
      sample_external_label: true,
      molecule_name: false,
      sample_index: true,
      svg: true,
    },
    "1848": {
      coefficient: true,
      yield_equivalent: true,
      molecule_sum_formula: true,
      sample_short_label: false,
      sample_name: true,
      sample_external_label: true,
      molecule_name: false,
      sample_index: true,
      svg: true,
    },
  },
};
export default displayMatrix;
